title: Benjamin Porter
description: My personal website 
email: mailto:bporter816@gmail.com
github_username: bporter816
github: https://github.com/bporter816
linkedin: https://linkedin.com/in/bporter816
markdown: kramdown
highlighter: rouge
