title: Benjamin Porter
description: My personal website 
email: bporter@cs.utexas.edu
email_action: mailto:bporter@cs.utexas.edu
github: https://github.com/bporter816
linkedin: https://www.linkedin.com/in/bporter816
parasol: https://parasol.tamu.edu
parasol_user: https://parasol.tamu.edu/people/bporter
markdown: kramdown
highlighter: rouge
