title: Benjamin Porter
description: My personal website 
email: bporter@cs.utexas.edu
email_link: mailto:bporter@cs.utexas.edu
github: https://github.com/bporter816
linkedin: https://www.linkedin.com/in/bporter816
markdown: kramdown
highlighter: rouge
timezone: America/Chicago
